### ISSUE TITLE
fix lighthouse performance score.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#3956]
<img width="847" alt="Screen Shot 2022-02-23 at 2 08 10 PM" src="https://user-images.githubusercontent.com/10232835/155417347-8aca7f84-7bcb-4275-a294-fffe83d30762.png">

### About the bug
Looking at lighthouse back at start of Nov 2021, the performance on page load was 61. Now over three months later, we are at 54. A brief review of PR scores indicates a drift downward (a.k.a. several culprits?).

### Useful links
https://web.dev/performance-scoring/
https://447063-216092618-gh.circle-artifacts.com/0/tmp/results.html (note: this link expires in ~24 days)

**Comment by genehynson** [comment]
update: they've gotten worse

![image](https://user-images.githubusercontent.com/6411855/198717082-929976a9-d6c3-4dbd-9695-ff9fda1992f3.png)

**Comment by genehynson** [comment]
@garylfowler @hralexander @wiedld can this issue be prioritized please? The lighthouse job has been failing and the metrics have not been reported into new tools for months. It seems like this issue has not been added to the QX team's project board. I fixed that.

**Comment by genehynson** [comment]
I noticed the `cloud-lighthouse` job stopped working in monitor-ci on Aug 9th.

**Comment by wiedld** [comment]
We have 2 things.
1. lighthouse scores not being reported in the monitoring dashboard.
   * specifically this commit: https://github.com/influxdata/ui/commit/79d25a4e09dd5f55ea17f5112e102153e45ed248
2. performance scores have been dropping
   * this was an unintended side effect of this work (see original tickets [here](https://github.com/influxdata/ui/issues/5819) and [here](https://github.com/influxdata/ui/issues/5687)). We did not have clarity that the original change was based on this performance need (tl;dr -- we should have included @genehynson in the convo).

**Comment by wiedld** [comment]
Decision made:
- [ ] turn off lighthouse as a default. Also have it be passed as an option to turn on.
- [ ] still get lighthouse working (if not a heavy lift).

**Comment by wiedld** [comment]
Conclusion -- it's a change in the cluster spun in the CI job, that led to the lighthouse job not working. Was not due to a UI or monitor-ci change. Likely culprit is in k8s-idpe; passed it over to deployments.


### Details:
When [this commit](https://github.com/influxdata/ui/commit/79d25a4e09dd5f55ea17f5112e102153e45ed248) was made, it changed what cluster was spun up for the lighthouse test. Before [it was](https://app.circleci.com/pipelines/github/influxdata/monitor-ci/14277/workflows/8731fea3-e255-440c-8748-0e92e4c04e6c/jobs/901629/parallel-runs/0/steps/0-109):
```
# start all nodes otherwise
docker-compose -f compose/fig.cloud.yml -f compose/fig.cypress.yml up -d 
[+] Running 0/0
 ⠋ vault Pulling     0.1s
 ⠋ jaeger Pulling    0.1s
 ⠋ postgres Pulling  0.1s
 ⠋ debug Pulling     0.1s
 ⠋ etcd Pulling      0.1s
 ⠋ redis Pulling     0.1s
...etc
```

And [after it became](https://app.circleci.com/pipelines/github/influxdata/monitor-ci/14284/workflows/110f9581-42a7-49e5-8d29-78da88edcbb8/jobs/902614/parallel-runs/0/steps/0-109):
```
# start all nodes otherwise
docker-compose -f compose/fig.cloud.yml -f compose/fig.cypress.yml up -d 
[+] Running 1/0
 ⠿ Network influx_application  Created 0.1s
 ⠋ Network influx_default      Creating 0.0s
[+] Running 2/2
 ⠿ Network influx_application     Created 0.1s
 ⠿ Network influx_default         Created 0.1s
 ⠋ Container influx-vault-1       Creating 0.0s
 ⠋ Container influx-jaeger-1      Creating 0.0s
 ⠋ Container influx-redis-1       Creating 0.0s
 ⠋ Container influx-api-docs-1    Creating 0.0s
 ⠋ Container influx-etcd-1        Creating 0.0s
 ⠋ Container influx-chronograf-1  Creating 0.0s
 ⠋ Container influx-postgres-1    Creating 0.0s
...etc
```

Then the lighthouse report produced `NaN`, which is why it failed on upload to the influxdata ingest endpoint.

Since the commit changed the login path, I don't think that impacts what cluster spins up. And there was no monitor-ci change. Dug into the cloud yml to track down which src changed (that it consumed), and it's likely an upstream k8s-idpe change. Kicked over to deployments.

**Comment by gaughen** [comment]
I have a question @wiedld - what happens if you revert Ari's change.  Do things start working again?
